---
- name: Ensure Cassandra directories exists
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ cassandra_user }}"
    group: "{{ cassandra_group }}"
    mode: "{{ item.mode | default('0755') }}"
  loop:
    - "{{ cassandra_data_dirs }}"
    - "{{ cassandra_log_dir }}"
    - "{{ cassandra_commitlog_dir }}"
    - "{{ cassandra_saved_caches_dir }}"
    - "{{ cassandra_hints_dir }}"

- name: Ensure Cassandra environment variables file exists
  ansible.builtin.template:
    src: env.j2
    dest: "{{ cassandra_env_file }}"
    state: present
    owner: root
    group: root
    mode: '0644'

- name: Apply custom Cassandra configuration
  ansible.builtin.template:
    src: cassandra.yaml.j2
    dest: "{{ cassandra_config_dir }}/cassandra.yaml"
    state: present
    owner: root
    group: root
    mode: '0644'

- name: Apply custom rackdc properties configuration
  ansible.builtin.template:
    src: cassandra-rackdc.properties.j2
    dest: "{{ cassandra_config_dir }}/cassandra-rackdc.properties"
    state: present 
    owner: root
    group: root
    mode: '0644'