---
- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_os_family }}.yml"

- name: System tasks
  import_tasks: system.yml

- name: OS-specific tasks
  include_tasks: "setup-{{ ansible_os_family }}.yml"

- name: Install Cassandra
  ansible.builtin.package:
    name: "{{ cassandra_packages }}"
    state: present

- name: Manage Cassandra configuration
  import_tasks: configure.yml

- name: Manage Cassandra service
  import_tasks: service.yml