---
- name: Install Cassandra systemd service unit
  ansible.builtin.template:
    src: cassandra.service.j2
    dest: /etc/systemd/system/cassandra.service
    owner: root
    group: root
    mode: '0644'

- name: Ensure Cassandra service is started and enabled on boot
  ansible.builtin.systemd:
    name: cassandra.service
    state: started
    enabled: yes
    daemon_reload: yes