---
galaxy_info:
  author: Florian Bobin
  description: Ansible role to deploy and manage Apache Cassandra database instance(s)
  license: MIT
  min_ansible_version: 5.0.0
  platforms: []
  galaxy_tags: []
dependencies: []